name: kaniko

on:
  push:
    branches: [ master ]

jobs:
  kaniko-build-images:
    strategy:
      matrix:
        device: [omnia]
        tag: [stable, latest]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "Kaniko build: selwtf/build-turris-base"
        uses: aevea/action-kaniko@v0.3.2
        with:
          image: selwtf/build-turris-base
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          extra_args: "--dockerfile toolchain/turris-base/dockerfile --build-arg DEVICE=${{ matrix.device }} --build-arg TAG=${{ matrix.tag }}"
